# Generated by Django 3.2 on 2022-05-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mae_reportes',
            name='csv',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='mae_reportes',
            name='excel',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='mae_reportes',
            name='pdf',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='I', max_length=1),
        ),
    ]
